[#sc-color-option]
= `SCColorOption`

Represents a color selection option represented by a color hex code string.

This option is intended to be used with a color picker type UI.

[source, python]
----
SCColorOption("my_option", "My Option", "My Group", "#ff0000")
----

[IMPORTANT]
--
This option type is state dependent and cannot be used on its own, it *MUST* be
registered to an SCLayer instance to be in any way useful.
--


== Properties

*Includes* <<sc-option-properties, SCOption Properties>>


=== `preview_image_name`

[cols="1m,9a"]
|===
| str
| The name of the preview image that was generated by this SCColorOption
instance.  The returned image is controlled by this option's `selection_value`.
|===


=== `selection_value`

[cols="1m,9a"]
|===
| str
| The current selection value for this SCColorOption instance.  This value will
be a hex color string.
|===


== Methods

=== `+__init__+`

Initializes the new SCColorOption with the given arguments.

[cols="1h,1m,8a"]
|===
| `key`
| str
| Key for this option.

| `name`
| str
| Display name for this option.

| `group`
| str
| Group name for this option.

| `default`
| str | CSHSL | CSRGB
| Default color value to use when no selection has yet been made by the user.
|===


=== `set_selection`

Sets the selection to the given value if and only if it is a valid hex color
string.

If the given value is _not_ a valid hex color string, this method will raise an
exception.

[cols="1h,1m,8a"]
|===
| value
| str
| Hex color string to set.
|===


=== `randomize`

Selects a "random" color option and sets the user selection to that value.
