[#sc-layer]
= `SCLayer`

Represents a single layer in a customizable sprite.

This layer has zero or more customization options provided at construction time
via named layer option keyword args.  The user's selections of those options are
then passed to the given `layer_provider` to construct the underlying
Displayable for the layer.

[source, python]
----
SCLayer("name", callback, option=("Option", [ "some", "choices" ]))

# OR

SCLayer("name", "my_image_{option}", option=("Option", [ "some", "choices" ]))
----


[#sc-layer-properties]
== Properties


=== `name`

[cols="1m,9a"]
|===
| str
| Name of the layer.
|===


=== `options`

[cols="1m,9a"]
|===
| <<sc-option>>[]
| List of options attached to this layer.
|===


=== `options_by_key`

[cols="1m,9a"]
|===
| dict
| Dict of option keys mapped to <<sc-option>> instances for all the options
attached to this layer.
|===


[#sc-layer-methods]
== Methods

=== `+__init__+`

[source, python]
----
def __init__(
    self,
    name: str,
    layer_provider: str|function,
    transform: function = None,
    **options: SCOption
)
----

Initializes the new `SCLayer` instance with the given arguments.

==== Arguments

[cols="1h,1m,8a"]
|===
| name
| str
| Internal name of the layer.  This value should be all lowercase and should
only contain letters, numbers, and underscores.

| layer_provider
| callable \| str
| Either a Layer Callback used to create the displayable that backs this layer,
or a template string containing `{var_name}` variables that will be injected
based on the selected options.

| transform
| callable \| None
| Optional transform function.  This function takes a Displayable as a single
argument and returns a Displayable.  Allows performing arbitrary transforms to
the whole layer regardless of option selections.

| **options
| kwargs
| Keyword arguments that define the options available to this layer.  Keyword
args must be one of the following types:

* An <<sc-opt>> instance.
* An <<sc-option>> instance.
* A tuple of 2 values: `(display_name, value_list)`
* A tuple of 3 values: `(display_name, group, value_list)`
|===
