[#custom-sprite-fac]
= CustomizedSpriteFactory

A factory which may be used to generate multiple <<custom-sprite>> instances
with the same base set of layers and options.

== Methods

=== `+__init__+`

Initializes a new CustomizedSpriteFactory instance with the given arguments.

==== Arguments

[cols="1h,1m,8"]
|===
| `*layers`
| <<sc-layer>>[]
| One or more layers from which <<custom-sprite>> instances should be created.
The layers are stacked on top of one another in the passed order. This means the
first given layer will be at the "back" of the sprite, where the last given
layer will be at the "front".

| `transform`
| callable
| An optional transform function that will be applied to the image created by
this factory.  This function should take a single
link:https://www.renpy.org/doc/html/displayables.html[Displayable] argument and
return a single Displayable value.
|===

=== `new_sprite`

Constructs a new `CustomizedSprite` instance with the given name.

==== Arguments

[cols="1h,1m,8"]
|===
| image_name
| str
| Name of the image that will be created for the returned sprite.  This name is
the value that will be used when referencing the sprite elsewhere in scripts via
`show`, `add`, etc..
|===

==== Returns

[cols="1m,9"]
|===
| <<custom-sprite>>
| A newly created CustomSprite instance.
|===