[#custom-sprite]
= CustomizedSprite

Represents a sprite image composed of customizable layers.

This type provides methods for manipulating the layers by changing their
customizations between each layer's configured customization options.

[source, python]
----
CustomizedSprite(
    "sprite_name",
    SCLayer(...),
    SCLayer(...),
    SCLayer(...)
)
----

== Properties

=== `layers`

A read-only list of all the SCLayer instances known to the current
<<custom-sprite>> instance.

=== `option_keys`

A list of all the option keys known to the <<custom-sprite>> instance.

.Example
[source, python]
----
my_sprite = CustomizedSprite(
    "sprite_name",
    SCLayer("skin", skin_cb, skin_color=SCOpt(...)),
    SCLayer("hair", hair_cb, hair_style=SCOpt(...)),
    SCLayer("eyes", eyes_cb, eye_color=SCOpt(...))
)

my_sprite.option_keys == [ 'skin_color', 'hair_style', 'eye_color' ]

----


=== `option_count`

The number of options known to the <<custom-sprite>> instance.

.Example
[source, python]
----
my_sprite = CustomizedSprite(
    "sprite_name",
    SCLayer("skin", skin_cb, skin_color=SCOpt(...)),
    SCLayer("hair", hair_cb, hair_style=SCOpt(...), hair_color=SCOpt(...)),
    SCLayer("eyes", eyes_cb, eye_color=SCOpt(...))
)

my_sprite.option_count == 4
----


=== `menu_components`

A dict of display name mapped to key for all options known to the
<<custom-sprite>> instance.

.Example Return Value
[source, python]
----
{
    "Hair Color": "hair_color",
    "Hair Style": "hair_style",
    ...
}
----

== Methods


=== `+__init__+`

Initializes the new <<custom-sprite>> instance with the given arguments.

==== Arguments

[cols="1h,1m,8"]
|===
| `image_name`
| str
| Name of the image that will be created for this sprite.  This name is the
value that will be used when referencing the sprite elsewhere in scripts via
`show`, `add`, etc...

| `*layers`
| <<sc-layer>>[]
| One or more layers from which the sprite should be created.  The layers are
stacked on top of one another in the passed order.  This means the first given
layer will be at the "back" of the sprite, where the last given layer will be at
the "front".
|===


=== `_require_option`

Requires that the given option key is known to the current <<custom-sprite>>
instance or one of its layers.

If the option key is not known, an exception will be thrown.

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option to require.
|===


=== `set_state`

Sets the internal state object of this <<custom-sprite>> instance to the given
<<sc-state>> instance.

==== Arguments

[cols="1h,1m,8"]
|===
| `state`
| <<sc-state>>
| State object to use for storing customization option selections.
|===


=== `inc_selection`

Increments the selection value for the target option.

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option for which the selection should be incremented.
|===


=== `dec_selection`

Deccrements the selection value for the target option.

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option for which the selection should be decremented.
|===


=== `get_option_display_name`

Returns the display name value for the target option.

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option for which the display name should be returned.
|===

==== Returns

[cols="1m,9"]
|===
| str
| Display name value for the target option.
|===


=== `get_option_selection`

Returns the current selection for the target option.

.Example
[source, python]
----
my_sprite.get_option_selection("hair_style") == 1
----

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option for which the display name should be returned.
|===

==== Returns

[cols="1m,9"]
|===
| int
| The selection value for the target option.
|===


=== `get_option`

Returns the <<sc-opt>> instance for the given option keyword.

.Example
[source, python]
----
my_sprite = CustomizedSprite(
    "sprite",
    SCLayer("hair", hair_cb, hair_style=SCOpt("Hair Style", [ "buns", "bob", "mohawk" ]))
)

print(my_sprite.get_option("hair_style").display_name) # Hair Style
----

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option for which the <<sc-opt>> instance should be returned.
|===

==== Returns

[cols="1m,9"]
|===
| <<sc-opt>>
| The target <<sc-opt>> instance.
|===


=== `get_option_value`

Returns the option value for the given option and selection.

.Example
[source, python]
----
my_sprite = CustomizedSprite(
    "sprite",
    SCLayer("hair", hair_cb, hair_style=SCOpt("Hair Style", [ "buns", "bob", "mohawk" ]))
)

my_sprite.get_option_value("hair_style", 2) == "bob"

----

==== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword of the option from which the target value should be returned.

| `selection`
| int
| `1` based index of the option value to return.
|===

==== Returns

[cols="1m,9"]
|===
| any
| Target option value.
|===
