# This `LayeredImage` is "based on" the customizable sprite generated by the
# `CustomizedSprite` configuration set up in `ccf_config.rpy`.
#
# While the options defined here could technically be used as options provided
# to the `CustomizedSprite`, it makes more sense to use a `LayeredImage` to
# allow easy control over the player's facial expressions.
layeredimage player:
    always:
        "player_base"

    group eyebrows:
        attribute angry_brows default:
            "images/ccp/brows/angry_brows.png"
        attribute relaxed:
            "images/ccp/brows/relaxed_brows.png"
        attribute sad:
            "images/ccp/brows/sad_brows.png"

    group mouth:
        attribute angry_mouth default:
            "images/ccp/mouth/angry_mouth.png"
        attribute grin:
            "images/ccp/mouth/grin_mouth.png"
        attribute sad:
            "images/ccp/mouth/sad_mouth.png"
        attribute smile:
            "images/ccp/mouth/smile_mouth.png"

layeredimage antagonist:
    always:
        "antagonist_base"

    group eyebrows:
        attribute angry_brows default:
            "images/ccp/brows/angry_brows.png"
        attribute relaxed:
            "images/ccp/brows/relaxed_brows.png"
        attribute sad:
            "images/ccp/brows/sad_brows.png"

    group mouth:
        attribute angry_mouth default:
            "images/ccp/mouth/angry_mouth.png"
        attribute grin:
            "images/ccp/mouth/grin_mouth.png"
        attribute sad:
            "images/ccp/mouth/sad_mouth.png"
        attribute smile:
            "images/ccp/mouth/smile_mouth.png"

# Create helpful little side images for showing who is talking!
#
# These side images are based on the layered images defined above so they will
# reflect the changes made to the sprites' mouths and eyebrows.
image side player = LayeredImageProxy("player", Transform(yoffset=350, xoffset=-50, zoom=0.7))
image side antagonist = LayeredImageProxy("antagonist", Transform(yoffset=350, xoffset=-50, zoom=0.7))


image classroom:
    "images/backgrounds/class.png"