= Ren'Py Sprite Customizer
:renpy-docs: https://www.renpy.org/doc/html

link:https://foxcapades.github.io/renpy-sprite-customizer/[Documentation] |
link:https://foxcapades.itch.io/renpy-sprite-customizer[Itch.io]


A pluggable sprite customization framework that allows the creation of any
number of playtime-customizable sprites using Ren'Py's
link:{renpy-docs}/layeredimage.html[LayeredImage]s.

The goal of this project is to allow game creators to plug in their own assets
and screens to set up character or sprite customization in their own games.

[IMPORTANT]
--
Presently this framework is only compatible with Ren'Py 8+ and Python 3.
--

video::https://raw.githubusercontent.com/Foxcapades/renpy-sprite-customizer/main/.assets/demo.webm[]


== Project Layout

=== link:game/customized_sprites.rpy[`customized_sprites.rpy`]

This is where the sprite customization options are defined.  This is the point
where your assets meet the library.


=== link:game/images.rpy[`images.rpy`]

Demonstration of using "normal" Ren'Py images in conjunction with customized
sprites.  This file defines some ``layeredimage``s that are based on customized
sprites and add expressions.


=== link:game/script.rpy[`script.rpy`]

The demo script that makes use of the sprite customizer library.


=== The Sprite Customizer Library

The sprite customizer library lives under the
link:game/lib/fxcpds/sprite_customizer[`game/lib/fxcpds/sprite_customizer`]
directory.

==== Config File

This file which lives at
link:game/lib/fxcpds/sprite_customizer/config.rpy[`game/lib/fxcpds/sprite_customizer/config.rpy`]
is the primary configuration for the sprite customizer.

This is where you go if you want to change the style of the sprite customization
screens.

==== The Customizer Directory

This directory is where the customizer screens and images are defined.  If you
intend to create your own character customization screens, this is a good place
to look to understand how the screens are built.

==== Everything Else

Everything else is library internals and shouldn't need to be touched unless you
want to hack the behavior of the sprite customizer.


== Credits

=== Resources Used

* Example Sprite Layers - https://butterymilk.itch.io/awfully-sweet
* Classroom Background - https://alte.itch.io/uncle-mugens-school
* Cover Image Background - link:https://www.freepik.com/free-vector/hand-drawn-floral-wallpaper_15680937.htm#query=floral%20background&position=2&from_view=keyword&track=ais[pikisuperstar on Freepik]

=== Contributors

Foxcapades::
image:docs/assets/github.svg[width=32, link="https://github.com/Foxcapades"]
image:docs/assets/itch-io.svg[width=32, link="https://foxcapades.itch.io/"]

GemmySystem::
image:docs/assets/github.svg[width=32, link="https://github.com/GemmySystem"]
image:docs/assets/itch-io.svg[width=32, link="https://gemmysystem.itch.io/"]
