import renpy  # type: ignore
from renpy.store import DynamicDisplayable, Solid  # type: ignore

from .option_ren import SCOption, SC_OPTION_TYPE_COLOR
from ..colors.cshsl_ren import CSHSL
from ..colors.csrgb_ren import CSRGB
from ..colors.csrgba_ren import CSRGBA
from ..utils.hex_color_ren import _validate_hex

"""renpy
init -1 python:
"""


class SCColorOption(SCOption):
    """
    # Sprite Customizer Color Option

    Represents a color selection option represented by a color hex code string.

    This option is intended to be used with a color picker type UI.

    ```python
    SCColorOption("my_option", "My Option", "My Group", "#ff0000")
    ```

    **IMPORTANT**: This option type is state dependent and cannot be used on its
    own, it **MUST** be registered to an SCLayer instance to be in any way
    useful.
    """

    def __init__(
        self,
        key: str,
        name: str,
        group: str | None,
        default: str | CSHSL | CSRGB,
    ):
        """
        Initializes the new SCColorOption with the given arguments.

        Arguments
        ---------
        key : str
            Key for this option.

        name : str
            Display name for this option.

        group : str | None
            Option group.  If this value is set to `None`, the `name` value will
            be used as the group name.

        default : str | CSHSL | CSRGB
            Default color value to use when no selection has yet been made by
            the user.
        """
        from uuid import uuid4
        super().__init__(key, name, group, SC_OPTION_TYPE_COLOR)

        if isinstance(default, str):
            _validate_hex(default)

            # If we have a hex string with alpha, trim out the alpha channel.
            if len(default) == 9:
                self._default = default[0:7]
            elif len(default) == 5:
                self._default = default[0:4]
            else:
                self._default = default

        elif isinstance(default, CSHSL):
            self._default = default.to_rgb().hex_string
        elif isinstance(default, CSRGBA):
            self._default = default.to_rgb().hex_string
        elif isinstance(default, CSRGB):
            self._default = default.hex_string
        else:
            raise Exception('"default" must be a string, a CSHSL instance, or a CSRGB instance')

        self._image_name = str(uuid4())

    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    #
    #   Properties
    #
    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

    @property
    def preview_image_name(self):
        """
        str
            The name of the preview image that was generated by this
            SCColorOption instance.  The returned image is controlled by this
            option's `selection_value`.
        """
        return self._image_name

    @property
    def selection_value(self) -> str:
        """
        str
            The current selection value for this SCColorOption instance.  This
            value will be a hex color string.
        """
        if not self._req_state().has_selection(self._key):
            self._state.set_selection(self._key, self._default)

        return self._state.get_selection(self._key)

    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    #
    #   SC-Internal Methods
    #
    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

    def _clone(self):
        return SCColorOption(self._key, self._name, self._group, self._default)

    def _post_clone(self):
        renpy.image(self._image_name, DynamicDisplayable(self._color_cb))

    # noinspection PyUnusedLocal
    def _color_cb(self, st: float, at: float):
        return Solid(self.selection_value), 0.0

    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
    #
    #   Public Methods
    #
    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

    def set_selection(self, value: str):
        """
        Sets the selection to the given value if and only if it is a valid hex
        color string.

        If the given value is _not_ a valid hex color string, this method will
        raise an exception.

        Arguments
        ---------
        value : str
            Hex color string to set.
        """
        if not isinstance(value, str):
            raise Exception('"value" must be a hex string')

        _validate_hex(value)
        self._req_state().set_selection(self._key, value)

    def randomize(self):
        """
        Selects a "random" color option and sets the user selection to that
        value.
        """
        self.set_selection(CSRGB(
            renpy.random.randint(0, 255),
            renpy.random.randint(0, 255),
            renpy.random.randint(0, 255),
        ).hex_string)
