= Ren'Py Sprite Customizer
:source-highlighter: highlight.js
:toc:
:toclevels: 3

This document is a WIP and presently is just a collection of notes about various
Sprite Customizer topics.  This document will eventually become the overall
documentation of the Sprite Customizer toolset.

== Topics

=== State

TODO

=== CustomizedSprite vs CustomizedSpriteFactory

The <<customized-sprite>> class may be constructed directly or via the
`CustomizedSpriteFactory` type.  Deciding whether to construct the type directly
or via the factory comes down to whether you want to create multiple sprites
from the same set of layers and options.

If you only wish to create a single sprite out of a given set of layers and
options, then it is fine to construct a new <<customized-sprite>> instance
directly.

If you wish to create more than one sprite out of a set of layers and options,
then it is best to create a `CustomizedSpriteFactory` from those layers and
options and use that factory instance to produce new <<customized-sprite>>
instances.

=== Layer Callbacks

A layer callback is a function that takes customization option values and
and returns a link:https://www.renpy.org/doc/html/displayables.html[Displayable]
to be used for the layer.  These callbacks are how the Sprite Customizer makes
use of your assets.

Customization option values are passed on parameters with names matching the
keyword args by which the backing `SCOpt` instances were passed to the relevant
<<sc-layer>>.

.Simple Example
[source, python]
----
def my_eyes_callback(eye_color, **kwargs):
    return f"images/sprites/eyes/{eye_color}.png"

define my_sprite = CustomizedSprite(
    "sprite",
    SCLayer("eyes", my_eyes_callback, eye_color=[ "green", "brown", "blue", "hazel" ])
)
----

Using the simple example above we have declared a callback that takes a single
argument, `eye_color` and returns the path to an image named with that value.

This argument directly relates to the kwarg `eye_color` passed to the
<<sc-layer>> constructor.

When the callback is executed, it will be passed one of the values from the
associated `SCOpt` value list.

.Complex Example
[source, python]
----
def my_hair_callback(hair_style, hair_color, **kwargs):
    return Transform("images/ccp/hair/{}.png".format(hair_style), matrixcolor=TintMatrix(hair_color))

SCLayer(
    "hair",
    my_hair_callback,
    hair_style=SCOpt("Hair Style", [ "straight", "curly", "bob", "mohawk" ]),
    hair_color=SCOpt("Hair Color", [ "#3d23e9", "#d0e1f5", "#aebce8", "#76b2e7" ])
)
----

In this, slightly more complex example, we have declared a callback that takes
two set arguments, `hair_style` and `hair_color`, then returns a
link:https://www.renpy.org/doc/html/transforms.html#transforms[Transform] that
applies a
link:https://www.renpy.org/doc/html/matrixcolor.html#TintMatrix[TintMatrix] to
a target image.

== Type Reference

[#custom-sprite]
=== `CustomizedSprite`

Represents a sprite image composed of customizable layers.

This type provides methods for manipulating the layers by changing their
customizations between each layer's configured customization options.

[source, python]
----
CustomizedSprite(
    "sprite_name",
    SCLayer(...),
    SCLayer(...),
    SCLayer(...)
)
----

==== Properties

===== `option_keys`

A list of all the option keys known to the `CustomizedSprite` instance.

===== `option_count`

The number of options known to the `CustomizedSprite` instance.

===== `menu_components`

A dict of display name mapped to key for all options known to the
`CustomizedSprite` instance.

[source, python]
----
{
    "Hair Color": "hair_color",
    "Hair Style": "hair_style",
    ...
}
----

==== Methods

TODO

[#custom-sprite-fac]
=== `CustomizedSpriteFactory`

[#sc-layer]
=== `SCLayer`

Represents a single layer in a customizable sprite.

This layer has zero or more customization options provided at construction time
via named <<sc-opt>> keyword args.  The user's selections of those options are
then passed to the given `layer_callback` to construct the underlying
link:https://www.renpy.org/doc/html/displayables.html[Displayable] for the
layer.

[source, python]
----
SCLayer("name", callback, option=SCOpt("Option", [ "some", "choices" ]))
----

==== Methods

===== `+__init__+`

Initializes the new `SCLayer` instance with the given arguments.

====== Arguments

[cols="1h,1m,8"]
|===
| `name`
| str
| Name of the layer.

| `layer_callback`
| function
| Callback used to create the
link:https://www.renpy.org/doc/html/displayables.html[Displayable] that backs
this layer.

| `**options`
| dict
| Dictionary of keyword arguments that define the options available to this
layer.  These keyword args must all be <<sc-opt>> values.
|===

===== `_require_option`

Requires that an option with the given key is known to this layer.  If no such
option is known, an exception will be thrown.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Key to the option to require.
|===

===== `_render`

A callback that is passed to the
link:https://www.renpy.org/doc/html/displayables.html#DynamicDisplayable[DynamicDisplayable]
instances built via the <<sc-lay-build-image>> method.

This method calls out to the configured `layer_callback` with the options
selected in the <<sc-state>>.

====== Arguments

[cols="1h,1m,8"]
|===
| `st`
| float
|

| `at`
| float
|

| `**kwargs`
| dict
| Keyword args that are passed through to the `layer_callback` function.
|===

====== Returns

This method returns a `(d, redraw)` tuple where:
[cols="1h,1m,8"]
|===
| `d`
| link:https://www.renpy.org/doc/html/displayables.html[Displayable]
| Displayable generated by the `layer_callback` function.

| `redraw`
| int\|float
| Maximum amount of time to wait before calling this method again.
|===


===== `clone`

Creates a copy of the current `SCLayer` instance.

====== Returns

A copy of the current `SCLayer` instance sans user state.

===== `set_state`

Replaces the user state store used by this `SCLayer` instance with the given
`SCState` object.

====== Arguments

[cols="1h,1m,8"]
|===
| `state`
| <<sc-state>>
| New state object to back this layer's customization option selections.
|===

===== `inc_selection`

Increments the user selection for the given option.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option whose selection should be incremented.
|===

===== `dec_selection`

Decrements the user selection for the given option.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option whose selection should be decremented.
|===

===== `get_option`

Returns the target <<sc-opt>> value from the current layer.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option to retrieve.
|===

====== Returns

The target <<sc-opt>> instance.

===== `get_option_value`

Returns the option value for the target option and selection.

====== Example

Given the layer:

[source, python]
----
layer = SCLayer("foo", bar, fizz=SCOpt("Buzz", [ "wing", "ding" ]))
----

the following would be true:

[source, python]
----
layer.get_option_value("fizz", 1) == "wing"
layer.get_option_value("fizz", 2) == "ding"
----

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option whose value should be returned.

| `selection`
| int
| `1` based index of the option value to retrieve.
|===

====== Returns

Returns the option value for the target option and selection.

===== `option_display_name`

Returns the display name for the target option.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option whose display name should be returned.
|===

====== Returns

The display name for the target option.

===== `option_selection`

Returns the use selected value for the target option.

====== Arguments

[cols="1h,1m,8"]
|===
| `option`
| str
| Keyword for the option whose value should be returned.
|===

====== Returns

The user selected value for the target option.

[#sc-lay-build-image]
===== `build_image`

Builds the
link:https://www.renpy.org/doc/html/displayables.html#DynamicDisplayable[DynamicDisplayable]
that represents this `SCLayer` instance.

====== Returns

The newly constructed
link:https://www.renpy.org/doc/html/displayables.html#DynamicDisplayable[DynamicDisplayable]
instance.


===== `build_attribute`

Builds a link:https://www.renpy.org/doc/html/layeredimage.html[LayeredImage]
https://www.renpy.org/doc/html/layeredimage.html#attribute[Attribute] instance
to represent this `SCLayer` instance.

====== Returns

The newly constructed
https://www.renpy.org/doc/html/layeredimage.html#attribute[Attribute] instance.


[#sc-opt]
=== `SCOpt`

Represents an option set for an <<sc-layer>>, providing options for customizing
that layer.

==== Properties

===== `display_name`

Display name for the set of options.

===== `option_values`

List of option values.

==== Methods

===== `+__init__+`

Initializes the new `SCOpt` object.

====== Arguments

[cols="1h,1m,8"]
|===
| `display_name`
| str
| Display name for the option group.

| `option_values`
| list
| List of values for the option group.
|===


[#sc-state]
=== `SCState`

This class defines an object that is used to hold sprite customization option
selections.  This is used to persist the selected options as part of the game
saves and reload those selections when loading the game from a save.

The state is a map of `1` based indexes of option values.

[source, python]
----
my_sprite_state = SCState()
my_sprite.set_state(my_sprite_state)
----

==== Methods


===== `+__init__+`

Initializes the new, blank `SCState` instance.


===== `get_selection`

Looks up the target selection value.  If the target selection value is unknown
to the `SCState` object, the value `1` will be recorded in the state and
returned from this method.

====== Arguments

[cols="1h,1m,8"]
|===
| `key`
| str
| Selection key.
|===

====== Returns

[cols="1m,9"]
|===
| int
| Current selection state for the given option key.
|===


===== `inc_selection`

Increments the selection value for the iven option to a maximum of `max`,
rolling back over to `1` if it would exceed that maximum.

====== Arguments

[cols="1h,1m,8"]
|===
| `key`
| str
| Key of the selection option whose value should be incremented.

| `max`
| int
| Max value the selection option can possibly be.
|===


===== `dec_selection`

Decrements the selection value for the given option to a minimum of `1`, rolling
over to `max` if it would go below `1`.

====== Arguments

[cols="1h,1m,8"]
|===
| `key`
| str
| Key of the selection option whose value should be decremented.

| `max`
| int
| Max value the selection option can possibly be.
|===
