= Ren'Py Sprite Customizer
:source-highlighter: highlight.js
:toc:
:toclevels: 4

This document is a WIP and presently is just a collection of notes about various
Sprite Customizer topics.  This document will eventually become the overall
documentation of the Sprite Customizer toolset.

== Topics

=== CustomizedSprite vs CustomizedSpriteFactory

The <<customized-sprite>> class may be constructed directly or via the
`CustomizedSpriteFactory` type.  Deciding whether to construct the type directly
or via the factory comes down to whether you want to create multiple sprites
from the same set of layers and options.

If you only wish to create a single sprite out of a given set of layers and
options, then it is fine to construct a new <<customized-sprite>> instance
directly.

If you wish to create more than one sprite out of a set of layers and options,
then it is best to create a `CustomizedSpriteFactory` from those layers and
options and use that factory instance to produce new <<customized-sprite>>
instances.

=== Layer Callbacks

A layer callback is a function that takes customization option values and
and returns a link:https://www.renpy.org/doc/html/displayables.html[Displayable]
to be used for the layer.  These callbacks are how the Sprite Customizer makes
use of your assets.

Customization option values are passed on parameters with names matching the
keyword args by which the backing `SCOpt` instances were passed to the relevant
`SCLayer`.

.Simple Example
[source, python]
----
def my_eyes_callback(eye_color, **kwargs):
    return f"images/sprites/eyes/{eye_color}.png"

define my_sprite = CustomizedSprite(
    "sprite",
    SCLayer("eyes", my_eyes_callback, eye_color=[ "green", "brown", "blue", "hazel" ])
)
----

Using the simple example above we have declared a callback that takes a single
argument, `eye_color` and returns the path to an image named with that value.

This argument directly relates to the kwarg `eye_color` passed to the `SCLayer`
constructor.

When the callback is executed, it will be passed one of the values from the
associated `SCOpt` value list.

.Complex Example
[source, python]
----
def my_hair_callback(hair_style, hair_color, **kwargs):
    return Transform("images/ccp/hair/{}.png".format(hair_style), matrixcolor=TintMatrix(hair_color))

SCLayer(
    "hair",
    my_hair_callback,
    hair_style=SCOpt("Hair Style", [ "straight", "curly", "bob", "mohawk" ]),
    hair_color=SCOpt("Hair Color", [ "#3d23e9", "#d0e1f5", "#aebce8", "#76b2e7" ])
)
----

In this, slightly more complex example, we have declared a callback that takes
two set arguments, `hair_style` and `hair_color`, then returns a
link:https://www.renpy.org/doc/html/transforms.html#transforms[Transform] that
applies a
link:https://www.renpy.org/doc/html/matrixcolor.html#TintMatrix[TintMatrix] to
a target image.

== Type Reference

[#customized-sprite]
=== `CustomizedSprite`

Represents a sprite image composed of customizable layers.

This type provides methods for manipulating the layers and changing their
customizations between each layer's configured customization options.

==== Properties

===== `option_count`

The total number of registered options across all layers.

===== `menu_components`

A dict of option display names to the matching option keyword.

[source, python]
----
{
    "Hair Style": "hair_style",
    "Hair Color": "hair_color",
    ...
}
----


==== Methods

===== `+__init__+`

Initializes a new `CustomizedSprite` instance with the given arguments.

====== Arguments

`image_name`::
    String name of the image that will be created for the sprite.  This name is
    the value that will be used when referencing the sprite image elsewhere in
    scripts via `show`, `add`, etc...

`layers`::
    One or more ``SCLayer``s from which the sprite should be created.  The
    layers are stacked on top of one another in the passed order.  This means
    the first given layer will be at the "back" of the sprite, where the last
    given layer will be at the "front".

===== `set_state`

Replaces the internal state object of the `CustomizedSprite` instance with the
given `SCState` instance.

====== Arguments

`state`::
A `SCState` object to use for storing customization option selections.
+
[source, python]
----
$ my_sprite_state = SCState()
$ my_sprite.set_state(my_sprite_state)
----


===== `inc_option`

Increments the selection value for the given option.

====== Arguments

`option`::
String key of the option for which the selection should be incremented.  This
key will be one of the `SCOpt` kwargs given to the `SCLayer` constructors.
+
[source, python]
----
$ my_sprite.inc_option("hair_style")
----


===== `dec_option`

Decrements the selection value for the given option.

====== Arguments

`option`::
String key of the option for which the selection should be decremented.  This
key will be one of the `SCOpt` kwargs given to the `SCLayer` constructors.
+
[source, python]
----
$ my_sprite.dec_option("hair_style")
----


===== `option_display_text`

Returns the display name for the target option.

====== Arguments

`option`::
String key of the option for which the display name should be returned.
+
[source, python]
----
$ display_name = my_sprite.option_display_text("hair_style")
----


===== `option_value_text`

Returns the selection value for the target option as a string.

====== Arguments

`option`::
Key of the option for which the selection value should be returned as a string.
+
[source, python]
----
$ selection = my_sprite.option_value_text("hair_style")
----


== Reference:

* link:https://www.renpy.org/doc/html/displayables.html#DynamicDisplayable[DynamicDisplayable]
* link:https://www.renpy.org/doc/html/layeredimage.html[LayeredImage]