= Ren'Py Sprite Customizer
:source-highlighter: highlight.js
:toc: left
:icons: font
:stylesheet: assets/readthedocs.css

:renpy-docs: https://www.renpy.org/doc/html

Documentation for the Sprite Customizer (SC) framework.

This document is a work in progress.

== Topics

=== Sprite State

To keep sprite customization options stored in game save files, the internal
selection state for the sprites is stored in a runtime variable of type
<<sc-state>>.

This state should be created via a runtime variable in a python line, or,
preferrably, a `default` statement.

[source, python]
----
default my_sprite_state_1 = SCState()
default my_sprite_state_2 = SCState()

label start:
    $ my_sprite_1.set_state(my_sprite_state_1)
    $ my_sprite_2.set_state(my_sprite_state_2)

label after_load:
    $ my_sprite_1.set_state(my_sprite_state_1)
    $ my_sprite_2.set_state(my_sprite_state_2)
----

This state is then loaded into a target <<custom-sprite>> instance to configure
all the option selections show the correct combination of options.  Each
separate <<custom-sprite>> instance should have it's own state instance.  This
means that for every unique sprite, you will need a unique `default` declaring a
new <<sc-state>> object.  Additionally, for every separate <<custom-sprite>>
instance, that state value must be loaded at `start` and `after_load` times.

[IMPORTANT]
--
This state value *MUST* be passed to the relevant sprite instance via the
`set_state` method in both the `start` and `after_load` labels.  If this is not
done, the sprites will reset to their default state.
--


=== Sprite vs. Factory

The <<custom-sprite>> class may be constructed directly or via the
<<custom-sprite-fac>> type.  Deciding whether to construct the type directly or
via the factory comes down to whether you want to create multiple sprites from
the same set of layers and options.

If you only wish to create a single sprite out of a given set of layers and
options, then it is fine to construct a new <<custom-sprite>> instance
directly.

If you wish to create more than one sprite out of a set of layers and options,
then it is best to create a <<custom-sprite-fac>> from those layers and options
and use that factory instance to produce new <<custom-sprite>> instances.

.Constructing a Single Sprite
[source, python]
----
my_sprite = CustomizedSprite(
    "protagonist",
    SCLayer("skin", ...),
    SCLayer("clothes", ...),
    SCLayer("hair", ...),
    SCLayer("eyes", ...)
)
----

.Constructing Multiple Sprites from the Same Options
[source, python]
----
sprite_fac = CustomizedSpriteFactory(
    SCLayer("skin", ...),
    SCLayer("clothes", ...),
    SCLayer("hair", ...),
    SCLayer("eyes", ...)
)

my_sprite_1 = sprite_fac.new_sprite("protagonist")
my_sprite_2 = sprite_fac.new_sprite("antagonist")
----


include::pages/topic-layer-callback.adoc[leveloffset=2]


== Type Reference

include::pages/custom-sprite.adoc[leveloffset=2]
include::pages/custom-sprite-fac.adoc[leveloffset=2]
include::pages/sc-layer.adoc[leveloffset=2]
include::pages/sc-opt.adoc[leveloffset=2]
include::pages/sc-state.adoc[leveloffset=2]