= Ren'Py Sprite Customizer
:source-highlighter: highlight.js
:toc: left
:icons: font
:stylesheet: assets/readthedocs.css

This document is a WIP and presently is just a collection of notes about various
Sprite Customizer topics.  This document will eventually become the overall
documentation of the Sprite Customizer toolset.

== Topics

=== State

To keep sprite customization options stored in game save files, the internal
selection state for the sprites is stored in a runtime variable of type
<<sc-state>>.

This state should be created via a runtime variable in a python line, or,
preferrably, a `default` statement.

[source, python]
----
default my_sprite_state_1 = SCState()
default my_sprite_state_2 = SCState()

label start:
    $ my_sprite_1.set_state(my_sprite_state_1)
    $ my_sprite_2.set_state(my_sprite_state_2)

label after_load:
    $ my_sprite_1.set_state(my_sprite_state_1)
    $ my_sprite_2.set_state(my_sprite_state_2)
----

This state is then loaded into a target <<custom-sprite>> instance to configure
all the option selections show the correct combination of options.  Each
separate <<custom-sprite>> instance should have it's own state instance.  This
means that for every unique sprite, you will need a unique `default` declaring a
new <<sc-state>> object.  Additionally, for every separate <<custom-sprite>>
instance, that state value must be loaded at `start` and `after_load` times.

[IMPORTANT]
--
This state value *MUST* be passed to the relevant sprite instance via the
`set_state` method in both the `start` and `after_load` labels.  If this is not
done, the sprites will reset to their default state.
--


=== CustomizedSprite vs CustomizedSpriteFactory

The <<custom-sprite>> class may be constructed directly or via the
<<custom-sprite-fac>> type.  Deciding whether to construct the type directly or
via the factory comes down to whether you want to create multiple sprites from
the same set of layers and options.

If you only wish to create a single sprite out of a given set of layers and
options, then it is fine to construct a new <<custom-sprite>> instance
directly.

If you wish to create more than one sprite out of a set of layers and options,
then it is best to create a <<custom-sprite-fac>> from those layers and options
and use that factory instance to produce new <<custom-sprite>> instances.

.Constructing a Single Sprite
[source, python]
----
my_sprite = CustomizedSprite(
    "protagonist",
    SCLayer("skin", ...),
    SCLayer("clothes", ...),
    SCLayer("hair", ...),
    SCLayer("eyes", ...)
)
----

.Constructing Multiple Sprites from the Same Options
[source, python]
----
sprite_fac = CustomizedSpriteFactory(
    SCLayer("skin", ...),
    SCLayer("clothes", ...),
    SCLayer("hair", ...),
    SCLayer("eyes", ...)
)

my_sprite_1 = sprite_fac.new_sprite("protagonist")
my_sprite_2 = sprite_fac.new_sprite("antagonist")
----


=== Layer Callbacks

A layer callback is a function that takes customization option values and
and returns a
link:https://www.renpy.org/doc/html/displayables.html[`Displayable`] to be used
for the layer.  These callbacks are how the Sprite Customizer makes use of your
assets.

Customization option values are passed on parameters with names matching the
keyword args by which the backing `SCOpt` instances were passed to the relevant
<<sc-layer>>.

.Simple Example
[source, python]
----
def my_eyes_callback(eye_color, **kwargs):
    return f"images/sprites/eyes/{eye_color}.png"

define my_sprite = CustomizedSprite(
    "sprite",
    SCLayer("eyes", my_eyes_callback, eye_color=[ "green", "brown", "blue", "hazel" ])
)
----

Using the simple example above we have declared a callback that takes a single
argument, `eye_color` and returns the path to an image named with that value.

This argument directly relates to the kwarg `eye_color` passed to the
<<sc-layer>> constructor.

When the callback is executed, it will be passed one of the values from the
associated `SCOpt` value list.

.Complex Example
[source, python]
----
def my_hair_callback(hair_style, hair_color, **kwargs):
    return Transform("images/ccp/hair/{}.png".format(hair_style), matrixcolor=TintMatrix(hair_color))

SCLayer(
    "hair",
    my_hair_callback,
    hair_style=SCOpt("Hair Style", [ "straight", "curly", "bob", "mohawk" ]),
    hair_color=SCOpt("Hair Color", [ "#3d23e9", "#d0e1f5", "#aebce8", "#76b2e7" ])
)
----

In this, slightly more complex example, we have declared a callback that takes
two set arguments, `hair_style` and `hair_color`, then returns a
link:https://www.renpy.org/doc/html/transforms.html#transforms[`Transform`] that
applies a
link:https://www.renpy.org/doc/html/matrixcolor.html#TintMatrix[`TintMatrix`] to
a target image.

== Type Reference

include::pages/custom-sprite.adoc[leveloffset=2]
include::pages/custom-sprite-fac.adoc[leveloffset=2]
include::pages/sc-layer.adoc[leveloffset=2]
include::pages/sc-opt.adoc[leveloffset=2]
include::pages/sc-state.adoc[leveloffset=2]